# Generated by Django 3.2.6 on 2021-08-16 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='منتشر شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
                ('status', models.BooleanField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='وضعیت')),
            ],
        ),
    ]
