# Generated by Django 3.2.6 on 2022-09-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسنه بندی ها'},
        ),
    ]
